- name: Ensure HAProxy binary has CAP_NET_BIND_SERVICE
  become: true
  when: haproxy_decision_setcap_net_bind_service | bool
  tags:
    - haproxy-decision
    - haproxy-decision-config
    - haproxy-decision-haproxy
  block:
    - name: Check HAProxy binary capabilities
      ansible.builtin.command: "getcap {{ haproxy_decision_binary_path }}"
      register: haproxy_decision_getcap
      changed_when: false
      failed_when: haproxy_decision_getcap.rc not in [0, 1]

    - name: Grant CAP_NET_BIND_SERVICE to HAProxy binary
      ansible.builtin.command: "setcap cap_net_bind_service=+ep {{ haproxy_decision_binary_path }}"
      when: "'cap_net_bind_service=ep' not in haproxy_decision_getcap.stdout"

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: "{{ haproxy_decision_config_template }}"
    dest: "{{ haproxy_decision_config_path }}"
    owner: "{{ haproxy_decision_config_owner }}"
    group: "{{ haproxy_decision_config_group }}"
    mode: "{{ haproxy_decision_config_mode }}"
  when: haproxy_decision_manage_config | bool
  notify: reload haproxy
  tags:
    - haproxy-decision
    - haproxy-decision-config
    - haproxy-decision-haproxy
