---
- name: Install HAProxy packages on Debian-based systems
  ansible.builtin.include_tasks: install-debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - haproxy-decision
    - haproxy-decision-install

- name: Install HAProxy packages on Red Hat-based systems
  ansible.builtin.include_tasks: install-redhat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - haproxy-decision
    - haproxy-decision-install
